### ISSUE TITLE
Tornar genérico 

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/tv-tools#1]
Interessante projeto.

O Index.html carrega a página que tem os conteúdos que serão mostrados, certo?
Pensaram em alguma forma de deixar essa Index customizável ?

**Comment by masakik** [comment]
O index redireciona para uma página externa que tem um sistema de notícias para a TV. Não lembro porque foi feito dessa forma. E um sistema legado que estamos atualizando.
