### ISSUE TITLE
pensar em um instalador para o cliente e para o servidor 

### ISSUE THREAD

**Issue by masakik** [uspdev/tv-tools#6]

**Comment by girol** [comment]
Eu posso pegar essa issue. Tenho também várias ideias de melhorias pra esse projeto :)

**Comment by girol** [comment]
Abrir uma issue para implementar instalador para o cliente. Estou assumindo que o cliente é o que vai ligar o computador via `wake on lan` de tempos em tempos

**Comment by girol** [comment]
Acabei fazendo dos dois aqui de uma vez uaehuahuehuae
